### ISSUE TITLE
iOS .AAE sidecar

### ISSUE THREAD

**Issue by b0rna** [andrewning/sortphotos#100]
Hi,

Since the --extensions flag is no longer supported, is there any way to sort iOS XML side car files along with the photos?

When importing photos from iOS, the sidecar AAE file is imported with the same name as the image. 
Example:

WIKR7898.JPG
WIKR7898.AAE

Thanks,

Borna

**Comment by Datapotomus** [comment]
In theory this should be fixed when my pull request gets approved, and the latest version of EXIFtool comes included. Just got to wait for the pull request to be approved.

**Comment by andrewning** [comment]
finally updated exiftool.  reopen if the sidecars don't work.
