### ISSUE TITLE
Exclude documents parameter (pdf, indd, rtf, doc, xls, zip...)

### ISSUE THREAD

**Issue by andreaseberharter** [andrewning/sortphotos#121]
Hi, 
first thank you very much for this great script, it works as expected! 

I was wondering if it would be possible to add a functions which allows to define an "excluded file type list". I was running sortphotos on 1TB external backup disk to move my images and videos neatly in place, but it also move all my other files such as pdfs, InDesign, zips etc. 

Is there a switch which allows that?

Thank you!
Andreas

**Comment by andrewning** [comment]
Currently it processes anything that exiftool processes and that includes things like pdf, etc. (https://exiftool.org/#supported).  This isn't built in, but there are two things you could do:
1) exiftool has an -ext flag where you can restrict the extensions it searches for.  You'd need to modify the command line arguments here: https://github.com/andrewning/sortphotos/blob/master/src/sortphotos.py#L277
2) or let exiftool process everything and ignore certain files later, like done here: https://github.com/andrewning/sortphotos/blob/master/src/sortphotos.py#L346

**Comment by andreaseberharter** [comment]
Thank you for your prompt reply - I will try to use the exiftool -ext flag. I am not so familiar with python to mess with the code though...

**Comment by gotiegithub** [comment]
Hi andrewning
Thanks for your great idea & code.

I'm facing the need described here.
I'm working with the second option you're providing, but it's taking too long to go over all the files.
I'd rather apply the first option - but it's not working for me.
I have added '--ext jpg' in the arguments, but when running your code I'm getting "Invalid TAG jpg".
I've tried to place it at several places, but same result.
Applying it directly to exiftool in CLI does the job, so the syntax should be correct, but in your code it doesn't work.

Any thoughts? 

Thanks in advance, g.

**Comment by Wicked0ne** [comment]
@gotiegithub 
I had the same issue as you, the "Invalid TAG" error. The trick is to put the ext option and extention into separate quotes. 

For example:
Bad:
[..., '-ext jpg', ...]
Good:
[..., '-ext', 'jpg', ...]

I hope this helps. As a added bonus I spent way too long creating a bunch of ext options for image and video file extentions. May as well share it here if others want to copy past it.

args = ['-j', '-a', '-G', '-ext', 'jpg', '-ext', 'jpeg', '-ext', 'jpe', '-ext', 'jif', '-ext', 'jfif', '-ext', 'jfi', '-ext', 'png', '-ext', 'apng', '-ext', 'gif', '-ext', 'webp', '-ext', 'tiff', '-ext', 'tif', '-ext', 'psd', '-ext', 'raw', '-ext', 'arw', '-ext', 'cr2', '-ext', 'nrw', '-ext', 'k25', '-ext', 'bmp', '-ext', 'dib', '-ext', 'heif', '-ext', 'heic', '-ext', 'ind', '-ext', 'indd', '-ext', 'indt', '-ext', 'jp2', '-ext', 'j2k', '-ext', 'jpf', '-ext', 'jpx', '-ext', 'jpm', '-ext', 'mj2', '-ext', 'svg', '-ext', 'svgz', '-ext', 'ai', '-ext', 'eps', '-ext', 'webm', '-ext', 'mpg', '-ext', 'mp2', '-ext', 'mpeg', '-ext', 'mpe', '-ext', 'mpv', '-ext', 'ogg', '-ext', 'mp4', '-ext', 'm4p', '-ext', 'm4v', '-ext', 'avi', '-ext', 'wmv', '-ext', 'mov', '-ext', 'qt', '-ext', 'flv', '-ext', 'swf', '-ext', '360', '-ext', '3gp', '-ext', '3gpp', '-ext', '3g2', '-ext', '3gp2', '-ext', 'arq', '-ext', 'arw', '-ext', 'asf', '-ext', 'avif', '-ext', 'dng', '-ext', 'gpr', '-ext', 'm2ts', '-ext', 'mts', '-ext', 'm2t', '-ext', 'ts', '-ext', 'mkv', '-ext', 'ogv']

**Comment by andreaseberharter** [comment]
@Ep0chalypse you might want to add another image extension to your list:  '-ext', 'nef',
