### ISSUE TITLE
NameError: name 'reload' is not defined

### ISSUE THREAD

**Issue by doodee123** [andrewning/sortphotos#131]
On a fresh install of Ubuntu 20.04 and using Python 3.8.5 I get the following error after running setup.py install

Traceback (most recent call last):
  File "sortphotos.py", line 27, in <module>
    reload(sys)
NameError: name 'reload' is not defined

**Comment by dbrandesky** [comment]
This appears to be related to issue #120. I don't know the proper fix, but I found that commenting out lines 27 and 28 in sortphotos.py seemed to fix it. Seems to only be an issue if you're using a non-English character set.

**Comment by andrewning** [comment]
The proper syntax for reload changed with more recent versions of python 3.  I don't think reload should be needed anyway.  I just took a short pull request without much thought since it was something harder for me to test directly.  I'll fix this later today.

**Comment by andrewning** [comment]
I reverted #120 as it isn't a proper fix for python 3.
