### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by madcoda9000** [andrewning/sortphotos#143]
Hello,
i have done the following:
1. loggged in as root (sudo su) (Ubuntu 20.04)
2. git clone https://github.com/andrewning/sortphotos.git
3. cd sortphotos
4. python setup.py install

I receive the following error:

`[06:26] root@blackhole:sortphotos# python setup.py install
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools
`

I hope anyone can help me.

**Comment by Sillium007** [comment]
Try installing setuptools prior to running setup.py

Depending on the python version:
sudo apt-get install python3-setuptools
sudo apt-get install python-setuptools

**Comment by madcoda9000** [comment]
Great. That worked for me.

Many thanks for that.

Sillium ***@***.***> schrieb am Mi., 30. Juni 2021, 13:40:

**Comment by Sillium007** [comment]
Could you mark the issue as closed?

**Comment by madcoda9000** [comment]
done :-)
