### ISSUE TITLE
sortphotos unable to locate exiftool

### ISSUE THREAD

**Issue by willtm** [andrewning/sortphotos#25]
Hello,

First of all, thank you for taking the time to develop and share `sortphotos.py`.  I really appreciate its simplicity.  That it's a python program makes it that much easier to use across a few different OSX and Linux machines I have.

I'm having trouble using the newest version.  Prior to the most recent version, I was able to use `sortphotos.py` to organize image files using the default settings.  I noticed yesterday that you updated the program to use Exiftool, so I installed it on my machine running OSX 10.10.  I confirmed that exiftool was located in `/usr/bin/exiftool` and used it to obtain metadata from an image file.

Next I tried using sortphotos:

`python sortphotos.py ~/Desktop/wedding\ photos/ ~/Desktop/test/`

I got the following error messge:

`Can't locate Image/ExifTool.pm in @INC (you may need to install the Image::ExifTool module) (@INC contains: Image-ExifTool/lib /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at Image-ExifTool/exiftool line 30.
BEGIN failed--compilation aborted at Image-ExifTool/exiftool line 30.
Traceback (most recent call last):
  File "sortphotos.py", line 150, in <module>
    args.recursive, args.copy, not args.silent, args.test)
  File "sortphotos.py", line 108, in sortPhotos
    e.execute(*args)
  File "sortphotos.py", line 29, in __exit__
    self.process.stdin.write("-stay_open\nFalse\n")
IOError: [Errno 32] Broken pipe`

It appears to be looking for exiftool or exiftool components.  But I've already confirmed that it's available to a regular user and that it works.  Can you advise me on how to troubleshoot this?  If this is a question that is better directed to exiftool forums, I apologize.  But because I've had no trouble with exiftool as such, I thought it might best to try here first.

**Comment by Mukhilm** [comment]
I pulled the latest version of the repository and I'm getting this same error (Can't locate Image/ExifTool/ISO.pm in @INC (you may need to install the Image::ExifTool::ISO module). I'm working in the same directory as sortphotos.py and the exif folder has the lib folder as well. Not sure what could be causing this problem but I'm running this on Ubuntu 20.04 with the latest version of perl 5.30
