### ISSUE TITLE
Ignore .* files (Hidden on Mac)

### ISSUE THREAD

**Issue by reidcooper** [andrewning/sortphotos#39]
Is there a way to ignore .* files? I keep getting those issues saying that the photos do not exist.

    IOError: [Errno 2] No such file or directory: u'/Volumes/USER/Pictures/Originals/2004/Pets/._IMG_1242.JPG'

Edit: I notice, that it happens right after it clears a directory and its the last one...I dont know if it happens to a normal photo though

Edit 2: It does not give the issue when using the copy command -c so I guess its up to the moving the files

**Comment by reidcooper** [comment]
I notice, that it happens right after it clears a directory and its the last one...I dont know if it happens to a normal photo though

**Comment by andrewning** [comment]
I can't replicate this.  If you have a simple directory (like 2-3 files) that you can replicate this on then I could debug it.

**Comment by reidcooper** [comment]
I am trying to replicate it right now. So far, I am trying to remember how it happened since it was back in March. When I was trying to organize the photos on my portable hard drive, that is where I got the issue. Not sure if it would be the read/write speeds of it or whatever, but that was the issue. I am going to see if I can retry it with a flash drive, otherwise, I wouldn't worry about this yet until I need to resort them on my hard drive but I don't know when that will be.

**Comment by reidcooper** [comment]
Alrighty, I was able to recreate the issue.

Here is a link to a zip folder of what I used to test it with. Inside, is two folders: First and Second. First has a couple of pictures of my bulldog for example. For some reason compressing the directory gets rid of the .* files so if you could create ._test_1.jpg, ._test_2.jpg, and so on for all 5 photos. You will get a directory listing of 

![listing](https://cloud.githubusercontent.com/assets/6921277/7569423/b100664c-f7d6-11e4-85bc-f171921d1486.png)

Make sure that all this is happening on a flash drive or a detachable media volume.******

Just run it from First Directory to Second Directory, or whatever you would like but as long as everything is happening on your flash drive or where ever that is a flash drive.

This is what I run and the output.

![output](https://cloud.githubusercontent.com/assets/6921277/7569503/376a7902-f7d7-11e4-8027-18e14b424085.png)

I hope that helps, let me know.

**Comment by andrewning** [comment]
Every time I've sat down to do this I realized my flash drive was at work.  Same today, so I couldn't reproduce this error.  But I modified the script so that it ignores all hidden files (starts with a dot). They aren't photos and must be some sort of metadata.  Hopefully that works for you.
