### ISSUE TITLE
keep filename while renaming

### ISSUE THREAD

**Issue by eephyne** [andrewning/sortphotos#43]
It could be nice to have a flag to use in the rename to be able to keep the original filename, like:

20141210_153415.DSC_2234.jpg 

One reason to that would be to be still able to look after duplicate and another is simply avoid two files taken exactly at the same second to collide.

**Comment by andrewning** [comment]
Collisions never happen. A digit is appending in those cases. Duplicates are looked at also. 




This could potentially be added but it's going to be a couple months before I have time to work on this and the other pending changes.

**Comment by eephyne** [comment]
I did it, you can use #f in the renaming string to add the filename (without extension of course)

the pull is here https://github.com/andrewning/sortphotos/pull/45
