### ISSUE TITLE
Cyrillic filenames issue

### ISSUE THREAD

**Issue by maxsl** [andrewning/sortphotos#47]
Script crashes at:
UnicodeEncodeError: 'ascii' codec can't encode characters in position

Traceback (most recent call last):
  File "./sortphotos.py", line 474, in <module>
    args.use_only_tags, not args.silent)
  File "./sortphotos.py", line 312, in sortPhotos
    sys.stdout.write('Source: ' + src_file + '\n')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 111-115: ordinal not in range(128)

**Comment by andrewning** [comment]
should hopefully be fixed with bbb3f93
