### ISSUE TITLE
Script fails after detecting duplicates and trying to overwrite

### ISSUE THREAD

**Issue by WillK0** [andrewning/sortphotos#49]
Hi there, first of thanks very much for this script, it is exactly what I want.

Unfortunately it seems to be having an issue with overwriting some of the duplicates. I should mention that I am asking it to sort through a large amount of photos on an external harddrive that is NTFS formatted.

Here's the error I get back:

Traceback (most recent call last):
  File "sortphotos.py", line 474, in <module>
    args.use_only_tags, not args.silent)
  File "sortphotos.py", line 304, in sortPhotos
    src_file, date, keys = get_oldest_timestamp(data, additional_groups_to_ignore, additional_tags_to_ignore)
  File "sortphotos.py", line 139, in get_oldest_timestamp
    exifdate = parse_date_exif(date)
  File "sortphotos.py", line 47, in parse_date_exif
    day = int(date_entries[2])
ValueError: invalid literal for int() with base 10: '38.37'

**Comment by andrewning** [comment]
This isn't a problem with duplicates but an unexpected format for the time stamp. Can you send me one of the photos that causes the problem? This symptom is easy to address but I'd like to get to the root of the problem.

**Comment by WillK0** [comment]
Hi there,

Apologies for not getting back sooner. This is the last file it was
processing prior to the error appearing. Thanks for getting back to me
about this.

All best,
Will

-------------

*Lockerbrook Outdoor Centre <http://lockerbrook.org.uk/> is 50! -* *Help
us fund raise for the next 50 years!
<https://www.justgiving.com/Lockerbrook50th/>*

Will Knight - 07908763780 - @Will_K0 <https://twitter.com/Will_K0>

**Comment by petesbrain** [comment]
i'll echo WillK0 here, this tool is great!  thanks much for your effort.

i seem to be running into the same issue.  would the erring image or any piece of it be of use?
```
Traceback (most recent call last):
  File "../dev/sortphotos/src/sortphotos.py", line 476, in <module>
    main()
  File "../dev/sortphotos/src/sortphotos.py", line 473, in main
    args.use_only_tags, not args.silent)
  File "../dev/sortphotos/src/sortphotos.py", line 305, in sortPhotos
    src_file, date, keys = get_oldest_timestamp(data, additional_groups_to_ignore, additional_tags_to_ignore)
  File "../dev/sortphotos/src/sortphotos.py", line 140, in get_oldest_timestamp
    exifdate = parse_date_exif(date)
  File "../dev/sortphotos/src/sortphotos.py", line 48, in parse_date_exif
    day = int(date_entries[2])
ValueError: invalid literal for int() with base 10: '40.23'
```

**Comment by WillK0** [comment]
Hi again,

I have realised since I sent this through to you that this picture may not
be the culprit. This picture was the last one it lists as being processed.
Did you get to the bottom of it by any chance?

All best,
Will

**Comment by andrewning** [comment]
Will,




Sorry, I haven’t had time to get to this yet.  I’ve seen another error like this, and I know what the problem is.  I have a fix in mind, but would like to have a photo to test.  Your photo probably work for this, just haven’t tested it yet.  Hopefully within a week...

**Comment by andrewning** [comment]
Will, 
I actually never found an attached file to test with, but I think this fix should address the issue.
- Andrew

**Comment by WillK0** [comment]
Hi Andrew,

I had sent through some more pictures but think I sent through too many so
attachment was too large to be accepted by github.

I'll test it out on those pictures when I get a chance.

Thanks again for you hard work, really enjoying having organised photos!
Now just need to actually go through them and get rid of one's I don't need.

All best,
Will
