### ISSUE TITLE
Option To Separate Photos with Missing or Invalid EXIF Data

### ISSUE THREAD

**Issue by dbxt** [andrewning/sortphotos#61]
Right now it appears that images with missing or invalid EXIF dates get defaulted to the current date.  It would be handy to be able to dump these photos into an `invalid_data` photo so they can be addressed.

If I get some time over the next few weeks I'll try to throw something together, but I figured I'd throw it out there to see if one of the more active devs wants to take a crack at it @nekopep.

**Comment by nekopep** [comment]
Can you send me privately such a photos with wrong EXIF data??
I find it usefull to have such options.

**Comment by dbxt** [comment]
Interestingly enough, I examined one of the images in question (my github profile photo that's over a year old) and the created date appears to be from the last time time it was sorted with this script.  Whatever modified the dates, the create date is now more current than the modified date.
````
    date:create: 2015-10-08T08:51:55-07:00

    date:modify: 2015-10-04T18:03:14-07:00
````
I haven't been through all of the code, but is this script updating the EXIF data or is this just a function of moving the files around?  In either case, something seems suspect. Here's the full dump of **identify -verbose 2015/10-Oct/2015_10_04_110314.jpeg**
````
Image: 2015/10-Oct/2015_10_04_110314.jpeg
  Format: JPEG (Joint Photographic Experts Group JFIF format)
  Mime type: image/jpeg
  Class: DirectClass
  Geometry: 200x200+0+0
  Resolution: 72x72
  Print size: 2.77778x2.77778
  Units: PixelsPerInch
  Type: TrueColor
  Endianess: Undefined
  Colorspace: sRGB
  Depth: 8-bit
  Channel depth:
    red: 8-bit
    green: 8-bit
    blue: 8-bit
  Channel statistics:
    Pixels: 40000
    Red:
      min: 0 (0)
      max: 255 (1)
      mean: 111.598 (0.437641)
      standard deviation: 62.4621 (0.244949)
      kurtosis: -0.62735
      skewness: 0.514409
      entropy: 0.965428
    Green:
      min: 0 (0)
      max: 255 (1)
      mean: 113.531 (0.445221)
      standard deviation: 59.0621 (0.231616)
      kurtosis: -0.493571
      skewness: 0.343778
      entropy: 0.962681
    Blue:
      min: 0 (0)
      max: 255 (1)
      mean: 111.269 (0.43635)
      standard deviation: 63.9293 (0.250703)
      kurtosis: -1.20507
      skewness: 0.110425
      entropy: 0.954346
  Image statistics:
    Overall:
      min: 0 (0)
      max: 255 (1)
      mean: 112.133 (0.439737)
      standard deviation: 61.8514 (0.242555)
      kurtosis: -0.797759
      skewness: 0.313905
      entropy: 0.960818
  Rendering intent: Perceptual
  Gamma: 0.454545
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Background color: white
  Border color: srgb(223,223,223)
  Matte color: grey74
  Transparent color: black
  Interlace: JPEG
  Intensity: Undefined
  Compose: Over
  Page geometry: 200x200+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: JPEG
  Quality: 90
  Orientation: Undefined
  Properties:
    date:create: 2015-10-08T08:51:55-07:00
    date:modify: 2015-10-04T18:03:14-07:00
    jpeg:colorspace: 2
    jpeg:sampling-factor: 1x1,1x1,1x1
    signature: 7bc2f842b239baab0c0f055c7d514122810d41d266196054b050af1b58afed50
  Artifacts:
    filename: 2015/10-Oct/2015_10_04_110314.jpeg
    verbose: true
  Tainted: False
  Filesize: 19.9KB
  Number pixels: 40K
  Pixels per second: 0B
  User time: 0.000u
  Elapsed time: 0:01.000
  Version: ImageMagick 6.9.2-0 Q16 x86_64 2015-08-18 http://www.imagemagick.org
````

Since the images in question have all been updated with current dates, I'll keep looking to find something with missing date.

**Comment by andrewning** [comment]
The script does not modify EXIF data.  It may however change a modified date but that's just a function of the file system.  Depending on what platform you are on (Windows, OS X, Linux) creation date means different things.  Personally I add the flag: "--ignore-groups File" so that if valid EXIF data is not provided then the photos aren't moved.  That functionality already exists.  Nothing gets defaulted to the current date.  It will fallback on file system dates if there is no EXIF data.  Those could be the current date if you copied files around.

**Comment by dbxt** [comment]
Excellent, that's exactly the information I needed.  From now on I'll use `--ignore-groups File` and deal with the files left over after the process is complete.  

Thanks for the quick response!

**Comment by andrewning** [comment]
Ok, great.  There are more details in [this section](https://github.com/andrewning/sortphotos#restrict-which-groupstags-to-search-through) of the README and links to all the filtering options you can use.

**Comment by dbxt** [comment]
That's the most polite version of "RTFM" I've ever seen. lol

Thanks for the hard work!
