### ISSUE TITLE
Encoding error in os.path.join

### ISSUE THREAD

**Issue by mapcuk** [andrewning/sortphotos#69]
I've got an exception during sorting photos on 365 line of src/sortphotos.py:

> dest_file = os.path.join(dest_file, filename)

'UnicodeError: ASCII encoding error: ordinal not in range(128) 
It turns out that filename was 'unicode' while dest_file is 'str'
I've fixed it by

> dest_file = os.path.join(dest_file, filename.encode('utf-8'))

OS:Ubuntu 12.04
Python 2.7
Environment:
LANG=ru_RU.UTF-8

**Comment by kron77** [comment]
I got that also on mac OS X Darwin 15.2.0 x86_64
Python 2.7.10
Environment:
LANG=en_GB.UTF-8

mapcuk's suggestion fixed it also

**Comment by andrewning** [comment]
ok great.  fixed with 3241453
