### ISSUE TITLE
Port to Python 3?

### ISSUE THREAD

**Issue by ChillarAnand** [andrewning/sortphotos#78]
Any thoughts on supporting Python 3?

**Comment by andrewning** [comment]
It should already work with Python 3, but maybe some things have changed.  I use Python 2 so I don't usually test on 3.  Where does it fail for you?

**Comment by andrewning** [comment]
I just pulled a pull request from a user on Python 3. See if that fixes it for you.

**Comment by ChillarAnand** [comment]
It works. Thanks :-)
