### ISSUE TITLE
Times after noon are truncated to noon.

### ISSUE THREAD

**Issue by jdforest** [andrewning/sortphotos#84]
With the following command:
sortphotos -r --rename %Y_%m%d_%H%M%S mysource/ mytarget/

All photos that were taken after 1200h are named with the correct year, month, and day but the hours and minutes are all 1200 followed by a sequential number because of the duplicate file names.

I have also tried this:
sortphotos -r --rename %Y_%m%d_%I%M%S%p mysource/ mytarget/

However, the same issue occurs. I have confirmed that the raw EXIF data are correct, so something must be going on in the reading of the 24-hour clock in Python.

I am using Debian testing and Python 2.7.13

**Comment by eirism** [comment]
Could you post the output when running the script with `sortphotos -t -r --rename %Y_%m%d_%H%M%S mysource/ mytarget/` (add the -t)? It is enough to run it on one picture of each "type", i.e. one taken before 1200h and one taken after.

**Comment by jdforest** [comment]
OK, so I have not tried this again since I posted the original comment, but it seems that the code must have been updated to use UTC. I tried it on a range of times (see output below); however, I am still not sure why the EXIF times and Access times are showing up 1-h different.

Output:

jdforest@sorex:~/Pictures$ sortphotos -t -r --rename %Y_%m%d_%H%M%S original/ test/
Preprocessing with ExifTool.  May take a while for a large number of files.
    1 directories scanned
    8 image files read
[{
  "SourceFile": "original/XT1F3450.JPG",
  "File:FileModifyDate": "2018:01:19 16:30:06-06:00",
  "File:FileAccessDate": "2018:04:19 10:43:22-05:00",
  "File:FileInodeChangeDate": "2018:04:19 10:43:17-05:00",
  "EXIF:ModifyDate": "2018:01:19 17:30:06",
  "EXIF:DateTimeOriginal": "2018:01:19 17:30:06",
  "EXIF:CreateDate": "2018:01:19 17:30:06"
},
{
  "SourceFile": "original/XT1F5488.JPG",
  "File:FileModifyDate": "2018:02:01 13:01:16-06:00",
  "File:FileAccessDate": "2018:04:19 10:39:09-05:00",
  "File:FileInodeChangeDate": "2018:04:19 10:34:47-05:00",
  "EXIF:ModifyDate": "2018:02:01 14:01:15",
  "EXIF:DateTimeOriginal": "2018:02:01 14:01:15",
  "EXIF:CreateDate": "2018:02:01 14:01:15"
},
{
  "SourceFile": "original/XT1F5051.JPG",
  "File:FileModifyDate": "2018:01:28 05:41:12-06:00",
  "File:FileAccessDate": "2018:04:19 11:00:47-05:00",
  "File:FileInodeChangeDate": "2018:04:19 11:00:39-05:00",
  "EXIF:ModifyDate": "2018:01:28 06:41:11",
  "EXIF:DateTimeOriginal": "2018:01:28 06:41:11",
  "EXIF:CreateDate": "2018:01:28 06:41:11"
},
{
  "SourceFile": "original/XT1F5844.JPG",
  "File:FileModifyDate": "2018:02:03 19:06:34-06:00",
  "File:FileAccessDate": "2018:04:19 11:00:47-05:00",
  "File:FileInodeChangeDate": "2018:04:19 10:59:55-05:00",
  "EXIF:ModifyDate": "2018:02:03 20:06:34",
  "EXIF:DateTimeOriginal": "2018:02:03 20:06:34",
  "EXIF:CreateDate": "2018:02:03 20:06:34"
},
{
  "SourceFile": "original/XT1F5485.JPG",
  "File:FileModifyDate": "2018:02:01 12:56:10-06:00",
  "File:FileAccessDate": "2018:04:19 10:39:09-05:00",
  "File:FileInodeChangeDate": "2018:04:19 10:34:47-05:00",
  "EXIF:ModifyDate": "2018:02:01 13:56:10",
  "EXIF:DateTimeOriginal": "2018:02:01 13:56:10",
  "EXIF:CreateDate": "2018:02:01 13:56:10"
},
{
  "SourceFile": "original/XT1F5477.JPG",
  "File:FileModifyDate": "2018:02:01 11:48:08-06:00",
  "File:FileAccessDate": "2018:04:19 10:39:09-05:00",
  "File:FileInodeChangeDate": "2018:04:19 10:34:47-05:00",
  "EXIF:ModifyDate": "2018:02:01 12:48:08",
  "EXIF:DateTimeOriginal": "2018:02:01 12:48:08",
  "EXIF:CreateDate": "2018:02:01 12:48:08"
},
{
  "SourceFile": "original/XT1F3447.JPG",
  "File:FileModifyDate": "2018:01:19 16:28:22-06:00",
  "File:FileAccessDate": "2018:04:19 10:43:54-05:00",
  "File:FileInodeChangeDate": "2018:04:19 10:43:17-05:00",
  "EXIF:ModifyDate": "2018:01:19 17:28:21",
  "EXIF:DateTimeOriginal": "2018:01:19 17:28:21",
  "EXIF:CreateDate": "2018:01:19 17:28:21"
},
{
  "SourceFile": "original/XT1F5483.JPG",
  "File:FileModifyDate": "2018:02:01 11:54:30-06:00",
  "File:FileAccessDate": "2018:04:19 10:39:09-05:00",
  "File:FileInodeChangeDate": "2018:04:19 10:34:47-05:00",
  "EXIF:ModifyDate": "2018:02:01 12:54:30",
  "EXIF:DateTimeOriginal": "2018:02:01 12:54:30",
  "EXIF:CreateDate": "2018:02:01 12:54:30"
}]
{ready}

[1/8] (TEST - no files are being moved/copied)
Source: original/XT1F3450.JPG
Date/Time: 2018-01-19 10:30:06
Corresponding Tags: File:FileModifyDate
Destination (move): test/2018/01-Jan/2018_0119_103006.jpg

[2/8] (TEST - no files are being moved/copied)
Source: original/XT1F5488.JPG
Date/Time: 2018-02-01 07:01:16
Corresponding Tags: File:FileModifyDate
Destination (move): test/2018/02-Feb/2018_0201_070116.jpg

[3/8] (TEST - no files are being moved/copied)
Source: original/XT1F5051.JPG
Date/Time: 2018-01-27 23:41:12
Corresponding Tags: File:FileModifyDate
Destination (move): test/2018/01-Jan/2018_0127_234112.jpg

[4/8] (TEST - no files are being moved/copied)
Source: original/XT1F5844.JPG
Date/Time: 2018-02-03 13:06:34
Corresponding Tags: File:FileModifyDate
Destination (move): test/2018/02-Feb/2018_0203_130634.jpg

[5/8] (TEST - no files are being moved/copied)
Source: original/XT1F5485.JPG
Date/Time: 2018-02-01 06:56:10
Corresponding Tags: File:FileModifyDate
Destination (move): test/2018/02-Feb/2018_0201_065610.jpg

[6/8] (TEST - no files are being moved/copied)
Source: original/XT1F5477.JPG
Date/Time: 2018-02-01 05:48:08
Corresponding Tags: File:FileModifyDate
Destination (move): test/2018/02-Feb/2018_0201_054808.jpg

[7/8] (TEST - no files are being moved/copied)
Source: original/XT1F3447.JPG
Date/Time: 2018-01-19 10:28:22
Corresponding Tags: File:FileModifyDate
Destination (move): test/2018/01-Jan/2018_0119_102822.jpg

[8/8] (TEST - no files are being moved/copied)
Source: original/XT1F5483.JPG
Date/Time: 2018-02-01 05:54:30
Corresponding Tags: File:FileModifyDate
Destination (move): test/2018/02-Feb/2018_0201_055430.jpg

**Comment by eirism** [comment]
What Modified date does the `stat` command give you for the files?
And is the EXIF date/time read correctly from the files? Could you check if other programs (picture viewer, file browser etc.) give the same EXIF Created date/time?

**Comment by jdforest** [comment]
Using stat, I get the date the file was moved into the test folder (i.e., today).
Access: 2018-04-19 12:24:27.623789754 -0500
Modify: 2018-04-19 12:24:01.935803965 -0500
Change: 2018-04-19 12:24:01.935803965 -0500

The EXIF data gives the the same times for the access/modify/inode times.

File Modification Date/Time     : 2018:04:19 12:24:01-05:00
File Access Date/Time           : 2018:04:19 12:24:27-05:00
File Inode Change Date/Time     : 2018:04:19 12:24:01-05:00
Modify Date                     : 2017:08:16 10:31:54
Date/Time Original              : 2017:08:16 10:31:54
Create Date                     : 2017:08:16 10:31:54

These all show local time (CDT). When I use sortphotos, the correct time is given to the file:
{
  "SourceFile": "original/b/XT1F1060.JPG",
  "File:FileModifyDate": "2018:04:19 12:24:01-05:00",
  "File:FileAccessDate": "2018:04:19 12:24:27-05:00",
  "File:FileInodeChangeDate": "2018:04:19 12:24:01-05:00",
  "EXIF:ModifyDate": "2017:08:16 10:31:54",
  "EXIF:DateTimeOriginal": "2017:08:16 10:31:54",
  "EXIF:CreateDate": "2017:08:16 10:31:54"
}
[1/10] (TEST - no files are being moved/copied)
Source: original/b/XT1F1060.JPG
Date/Time: 2017-08-16 10:31:54
Corresponding Tags: EXIF:DateTimeOriginal, EXIF:CreateDate, EXIF:ModifyDate
Destination (copy): test3/2017/08/2017_0816_103154.jpg


However, another file, taken when daylight savings was off and in another time zone (I did not change the clock in the camera, so it should have read CST -- there is no GPS in the camera):

stat:
Access: 2018-04-19 14:58:32.010153362 -0500
Modify: 2018-01-19 16:30:06.000000000 -0600
Change: 2018-04-19 11:39:50.820009021 -0500

EXIF:
File Modification Date/Time     : 2018:01:19 16:30:06-06:00
File Access Date/Time           : 2018:04:19 14:58:32-05:00
File Inode Change Date/Time     : 2018:04:19 11:39:50-05:00
Modify Date                     : 2018:01:19 17:30:06
Date/Time Original              : 2018:01:19 17:30:06
Create Date                     : 2018:01:19 17:30:06




{
  "SourceFile": "test2/2018/01/2018_0119_103006.jpg",
  "File:FileModifyDate": "2018:01:19 16:30:06-06:00",
  "File:FileAccessDate": "2018:04:19 14:58:32-05:00",
  "File:FileInodeChangeDate": "2018:04:19 11:39:50-05:00",
  "EXIF:ModifyDate": "2018:01:19 17:30:06",
  "EXIF:DateTimeOriginal": "2018:01:19 17:30:06",
  "EXIF:CreateDate": "2018:01:19 17:30:06"
}
[1/3] (TEST - no files are being moved/copied)
Source: test2/2018/01/2018_0119_103006.jpg
Date/Time: 2018-01-19 10:30:06
Corresponding Tags: File:FileModifyDate
Destination (copy): test3/2018/01/2018_0119_103006.jpg

**Comment by eirism** [comment]
The script seems to be doing the right thing with the data it has (stat + EXIF), except for the conversion to UTC (see #94). It chooses the oldest time and uses it for the time stamp.

I do not know the reason for the 1h difference in the EXIF and filesystem time. It could be something the camera did or something that happened when transferring the file to your computer.

**Comment by jdforest** [comment]
OK, I will see what is going on with the files. Thanks for your help.
