### ISSUE TITLE
Possible to add HEIC (ios 11 pics?)

### ISSUE THREAD

**Issue by wtrdk** [andrewning/sortphotos#86]
Hi,

I really love your script!
Is it possible to add HEIC format to the script? (The new iOS 11 format)
I would love to include it myself, but I'm no developer... ;-)

Thanks

**Comment by andrewning** [comment]
We'd have to wait until exiftool (https://sno.phy.queensu.ca/~phil/exiftool/) was updated to support heic files.  Sortphotos depends on that tool to extract the photo metadata.

**Comment by wtrdk** [comment]
Thanks for your repy!
Ah, of course! Could have guessed it myself! Well, I hope that they add
HEIC support.
For now, I've written a basic bash script that sorts the HEIC. Not nearly
as flexible and nice as your script, but it works for now.

2017-09-14 6:12 GMT+02:00 andrewning <notifications@github.com>:

**Comment by andrewning** [comment]
Currently it should work for heic (I've not tested) but it would only look at things like file creation date. Exiftool would be required to sort using the exif data.

**Comment by hnarayanan** [comment]
In case you're still interested in this, I just wanted to let you know:

I simply went to [Paul Harvey's website](https://www.sno.phy.queensu.ca/~phil/exiftool/) and downloaded a more recent version of the tool (the .tar.gz file). Then untarred it and renamed the folder to match what is in the source tree of this app, and replaced it.

Then running `sortphotos` "just worked." Great work @andrewning!

**Comment by triantos** [comment]
I also tried replacing ExifTool with an updated version. ExifTool supports HEIC but it looks like sortphotos still skips files of that type. If you can make a quick update to support this, I'd appreciate it!

**Comment by andrewning** [comment]
updated.  sorry for delay.
