### ISSUE TITLE
Is it possible to include the original file name in a renamed file?

### ISSUE THREAD

**Issue by andreaseberharter** [andrewning/sortphotos#95]
I have several pictures which have been taking exactly at the same time and minute:

4P1B9332.JPG
4P1B9333.JPG
4P1B9334.JPG
4P1B9335.JPG
4P1B9336.JPG
4P1B9337.JPG
4P1B9338.JPG
4P1B9339.JPG

running this command:

sortphotos --test --recursive --rename %Y-%m-%d_%H%M /PICTURE-SOURCE /SORT-PHOTOS

renames the pictures to:

2015/11-Nov/2015-11-25_1645.jpg 
2015/11-Nov/2015-11-25_1645_1.jpg 
2015/11-Nov/2015-11-25_1645_2.jpg 
2015/11-Nov/2015-11-25_1645_3.jpg 
2015/11-Nov/2015-11-25_1645_4.jpg 
2015/11-Nov/2015-11-25_1645_5.jpg 
...

It would be great to include the original file name in the rename operation. Is this possible? 

Thanks, Andreas

**Comment by andrewning** [comment]
I've not implemented that functionality, but this repo has a lot of forks and I'm pretty sure some of them have added this.

**Comment by Sillium007** [comment]
I added a change which should do what you are asking for -> #96

**Comment by andreaseberharter** [comment]
Thank you Andrew. 

Thank you Sillium007! 👍 

If I understand your code change correctly, you added the original filename in case of duplication instead of increasing the number. 

In fact it would be nice to have both, adding the filename by default and increasing the number. I just ran some test with my ~800GB picture database and I think I would need both options to be safe :D

**Comment by Sillium007** [comment]
So you want the output to be like:
2015/11-Nov/2015-11-25_1645_4P1B9332_1.jpg
2015/11-Nov/2015-11-25_1645_4P1B9333_2.jpg

? :)

**Comment by andreaseberharter** [comment]
Yes, more like this:

2015/11-Nov/2015-11-25_1645_4P1B9332_1.jpg
2015/11-Nov/2015-11-25_1645_4P1B9332_2.jpg
2015/11-Nov/2015-11-25_1645_4P1B9332_3jpg

I saw that I have in several different folders images with the same names. 

Maybe this is overcomplicating things, because with the timestamp this should not happen anyway... I guess I will also add the seconds to the renaming pattern.

**Comment by Sillium007** [comment]
I added another (untested) commit to append the originalfilename + an increasing number to the pull request #96 
Hope this helps :)

**Comment by andrewning** [comment]
merged

**Comment by andreaseberharter** [comment]
Thanks!
